### ISSUE TITLE
Please showcase my Nuxt site, Wandsworth Town

### ISSUE THREAD

**Issue by bovas85** [nuxt-community/awesome-nuxt#102]
It's a static Nuxt.js site hosted on our servers, using PWA module, static generation and WordPress REST API.

Site link:

[https://wandsworth.town](https://wandsworth.town)

**Comment by limichange** [comment]
what's the website description? If you want to show it, you need to give me the description of the website.

**Comment by bovas85** [comment]
here it is, thanks
Wandsworth Town Business Improvement District (BID) puts businesses at the heart of what we do; shaping the future of Wandsworth Town. We aim to boost the economy of the town centre as a whole, by promoting local events and offers and increasing footfall in the area.

**Comment by limichange** [comment]
😅 too long. Could I just put the first sentence?

**Comment by bovas85** [comment]
Yes indeed 🗡 Wandsworth Town Business Improvement District (BID) puts businesses at the heart of what we do; shaping the future of Wandsworth Town.
