### ISSUE TITLE
Please add to showcase this site using Nuxt

### ISSUE THREAD

**Issue by bovas85** [nuxt-community/awesome-nuxt#105]
Site link: https://antilophia.com
Description: Antilophia offers a boutique luxury travel service, delivering carefully crafted travel experiences within Africa & the Indian Ocean and Latin America & the Caribbean.

Tech: Nuxt.js, WordPress REST API

**Comment by bovas85** [comment]
Not everyone can do PR, it might be I'm not a Developer or perhaps the other two sites we did were added by you and I kept following the same approach?

**Comment by manniL** [comment]
@bovas85 I don't see why someone who can post an issue can't create a PR. Even if that person is no developer, he is definitely able to C&P a link from the list and to alter the content. :relaxed:
