### ISSUE TITLE
Feathers - Nuxt template

### ISSUE THREAD

**Issue by woodgates** [nuxt-community/awesome-nuxt#154]
Hi.

I created a Feathers Nuxt template here "https://github.com/woodgates/feathers-nuxt". Its more complete than the one that is generated with the "nuxt-create-app" as I used the feathers-cli. It also has the dependencies updated.

I just want to share it but I don't know how. New in this.

B/R

**Comment by limichange** [comment]
thanks， I will add it.

**Comment by limichange** [comment]
Done
