### ISSUE TITLE
Looking for a Nuxt 2 tutorial, but lot's of Nuxt 1 tutorials are listed

### ISSUE THREAD

**Issue by ahus1** [nuxt-community/awesome-nuxt#215]
I was looking for a good Nuxt 2 tutorial to link to, but the majority of links lead to Nuxt 1 tutorials that first install Vue CLI. 

I wonder if the old tutorials should be purged from the list?

**Comment by limichange** [comment]
🤔Mybe we should add version label. like `v1` and `v2`.

**Comment by manniL** [comment]
@limichange Nice idea! 👍
