### ISSUE TITLE
Nuxt + CoreUI Starter Kit

### ISSUE THREAD

**Issue by muhibbudins** [nuxt-community/awesome-nuxt#222]
Hi there,

I create this starter kit ([Nuxt + CoreUI](https://github.com/muhibbudins/nuxt-coreui)) a months ago, but i forgot to open issue here. 😁 

Hopefully you can insert this project to the awesome list. 😄 

> Description :
> **NuxtJS + CoreUI Starter Kit** - Unofficial Nuxt + CoreUI project, free to use boilerplate for every need.

Thanks in advance

**Comment by limichange** [comment]
added.
