### ISSUE TITLE
awesome-nuxt logo

### ISSUE THREAD

**Issue by dennis47528** [nuxt-community/awesome-nuxt#303]
I made a logo for awesome-nuxt. 🎉😎
Inspired by https://github.com/vuejs/awesome-vue.
The new logo fits better in my opinion.

Let me know if you like it. Any suggestions?
Should i make a pull request?

## New logo:

![awesome-nuxt-logo](https://user-images.githubusercontent.com/33426785/66664804-8b95d480-ec4d-11e9-915c-86afc16b1f56.png)

**Comment by limichange** [comment]
GJ, welcome to PR.

**Comment by limichange** [comment]
![image](https://user-images.githubusercontent.com/1947344/67776223-00b13880-fa9b-11e9-8068-6e0a1505fd01.png)
I fond some white point. Please fix it.

**Comment by dennis47528** [comment]
This is just a screenshot 😄. I have a proper svg file.

**Comment by limichange** [comment]
👍
