### ISSUE TITLE
External scripts not rendering on page navigates

### ISSUE THREAD

**Issue by imranr970** [nuxt-community/awesome-nuxt#359]
Hi! I want to add external scripts in my nuxt app and please note on all over app not in single page.
There are multiple scripts. Those work fine on initial page load. But when I navigate to some other route external scripts does not work and disable some functionality. I tried to add vue-meta callback strategy in default.vue but that does not work as well. Please some one guide me. This is a serious issue right now I am facing.
Thanks in advance.

**Comment by limichange** [comment]
sorry, please  https://discordapp.com/invite/ps2h6QT to discuss your question.
