### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Sambhrama754** [nuxt-community/awesome-nuxt#474]
A question:who is the youngest person to write nuxt js?
I think 🤔 I am cause I was ten year old when I made this project? But now i am 11
Link to the repo:[Repo](https://github.com/Sambhrama754/basaveshwar-hardwares)

**Comment by pi0** [comment]
Hi @Sambhrama754. You can join our discord to chat https://discord.nuxtjs.org/ :)
