### ISSUE TITLE
Deprecated project

### ISSUE THREAD

**Issue by BrendonHenrique** [nuxt-community/awesome-nuxt#484]
Hey just a heads up , the project called laravel-nuxt-js that is finded in the list 
is currently deprecated , visiting repo you can find out this : 
"This repository has been archived by the owner. It is now read-only."

**Comment by Geminii** [comment]
Hi @BrendonHenrique 👋 
Thanks for your feedback, I will remove it from the list. 
Don't hesitate to provide a list of unmaintain module / showcase 👍

**Comment by Geminii** [comment]
Resolves in this [commit](https://github.com/nuxt-community/awesome-nuxt/commit/94e21453fd5dd9bb240e868435d046246d4772f5)
