### ISSUE TITLE
Hot do I add a template to nuxt-community?

### ISSUE THREAD

**Issue by nekdolan** [nuxt-community/awesome-nuxt#54]
Hi guys,

I am not very familiar with github or the community.
Could someone tell me how to get this template: https://github.com/nekdolan/express-template-hot 
into the list?

Thanks in advance

**Comment by limichange** [comment]
First, install vue-cli. It is a cli tool that help you download template.
```
$ npm install -g vue-cli
```

Then you can init your project.
```
vue init nuxt-community/express-template <project-name>
cd <project-name> # move to your project
npm install # or yarn install
```

**Comment by limichange** [comment]
You want to create a PR?

**Comment by limichange** [comment]
@nekdolan You can look this https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by nekdolan** [comment]
Thanks. Hopefully I did it right: https://github.com/nuxt-community/awesome-nuxt/pull/55

**Comment by limichange** [comment]
All thing is right, good.
