### ISSUE TITLE
Improve awesome-nuxt

### ISSUE THREAD

**Issue by pi0** [nuxt-community/awesome-nuxt#6]
Hey. I've some suggestions improving awesome-nuxt. First i think it would be better adding some description in front of links (Just like [awesome-vue](https://github.com/vuejs/awesome-vue)) Also we are going to have more modules from community where some of them are unofficial but really awesome. Suggest listing both official and non-official ones here too (I can help listing some)

Another interesting idea is that in future we may add an official store like section to nuxt website for templates and modules. Having seperated DB for awesome and that may be an extra job missing consistensy. Awesome is awesome, We may follow some conventions like [vue-curated](https://github.com/vuejs/vue-curated/blob/master/PACKAGES.md) to add links to important meta such as link, docs, badge, status, stablitiy and official so a [graphql server](https://github.com/vuejs/vue-curated-server) can easily serve data right from this repo.
BTW nice job @limichange so far <3

Appendix: Here is link to [Vue-Curated](https://curated.vuejs.org). We may fork and host it for nuxt for free :D

/ping @alexchopin @Atinux

**Comment by limichange** [comment]
I get it. I will update some description as soon as.

**Comment by alidcastano** [comment]
Any decision on how should modules be included?

Also, is it possible to use Nuxt.js with Apollo yet? I saw this issue https://github.com/nuxt/nuxt.js/issues/504 last time I looked into it.

**Comment by Atinux** [comment]
I should work with the next release, I will have to take a look at it!

**Comment by manniL** [comment]
Stale :man_shrugging:
