### ISSUE TITLE
Create a new section for non-module tools

### ISSUE THREAD

**Issue by mootari** [nuxt-community/awesome-nuxt#92]
[nuxt-generate-cluster](https://github.com/nuxt-community/nuxt-generate-cluster) still needs a home in this list. While it's "official", it is not a module.

Suggested variants:
1. Ignore the fact that it's not a module and put it under "Modules > Official" (at least until more libraries get added that warrant a new section).
2. Create a new section "Tools" and reserve it for official and community contributions.
3. Create a new section "Tools" with a subsection "Official".

Thoughts?

**Comment by limichange** [comment]
ok, I get it. Thanks for your suggestion. 😗

**Comment by mootari** [comment]
> Thanks for your suggestion.

Just doing my part to reduce mental effort. ✊💪

**Comment by limichange** [comment]
I thought for a minute that we don't need create a subsection "Official". Such as

 - adonuxt
 - nuxt-community/adonuxt

**Comment by mootari** [comment]
So, option 2?

**Comment by limichange** [comment]
yep
